config/routes.rb
Rails.application.routes.draw do
  resources :dissertations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dissertation.rb
class Dissertation < ApplicationRecord

  enum kind: { admin: 0, direito: 1, educacao: 2, odontologia: 3, family: 4 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dissertations_controller.rb
class DissertationsController < ApplicationController
  before_action :set_dissertation, only: %i[ show edit update destroy ]

  # GET /dissertations or /dissertations.json
  def index
    @dissertations = Dissertation.order(year: :desc).page(params[:page]).per(30)
  end

  # GET /dissertations/1 or /dissertations/1.json
  def show
  end

  # GET /dissertations/new
  def new
    @dissertation = Dissertation.new
  end

  # GET /dissertations/1/edit
  def edit
  end

  # POST /dissertations or /dissertations.json
  def create
    @dissertation = Dissertation.new(dissertation_params)

    respond_to do |format|
      if @dissertation.save
        format.html { redirect_to dissertation_url(@dissertation), notice: "Dissertation was successfully created." }
        format.json { render :show, status: :created, location: @dissertation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dissertation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dissertations/1 or /dissertations/1.json
  def update
    respond_to do |format|
      if @dissertation.update(dissertation_params)
        format.html { redirect_to dissertation_url(@dissertation), notice: "Dissertation was successfully updated." }
        format.json { render :show, status: :ok, location: @dissertation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dissertation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dissertations/1 or /dissertations/1.json
  def destroy
    @dissertation.destroy

    respond_to do |format|
      format.html { redirect_to dissertations_url, notice: "Dissertation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dissertation
      @dissertation = Dissertation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dissertation_params
      params.require(:dissertation).permit(:name, :title, :date, :link, :evaluations, :kind, :year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dissertations_helper.rb
module DissertationsHelper
end

app/views/dissertations/_dissertation.html.erb
<tr id="<%= dom_id dissertation %>" class="align-middle">
  <td class="text-center align-middle">
    <%= dissertation.year %>
  </td>
  <td class="text-center align-middle">
    <%= dissertation.name %>
  </td>
  <td class="text-center align-middle">
    <%= dissertation.title&.html_safe %>
  </td>
  <td class="text-center align-middle">
    <%= dissertation.link %>
  </td>
  <td class="text-center align-middle">
    <%= dissertation.evaluations %>
  </td>
</tr>

app/views/dissertations/_form.html.erb
<%= form_with(model: dissertation) do |form| %>
  <% if dissertation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dissertation.errors.count, "error") %> prohibited this dissertation from being saved:</h2>

      <ul>
        <% dissertation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.label :evaluations, style: "display: block" %>
    <%= form.text_field :evaluations %>
  </div>

  <div>
    <%= form.label :kind, style: "display: block" %>
    <%= form.number_field :kind %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.text_field :year %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dissertations/edit.html.erb
<h1>Editing dissertation</h1>

<%= render "form", dissertation: @dissertation %>

<br>

<div>
  <%= link_to "Show this dissertation", @dissertation %> |
  <%= link_to "Back to dissertations", dissertations_path %>
</div>

app/views/dissertations/index.html.erb
<%- model_class = Dissertation -%>
<%= content_for :page_header do %>
<% end %>
<h3 class="fs-4">MESTRADO EM ADMINISTRAÇÃO E DESENVOLVIMENTO EMPRESARIAL</h3>
<div class="table-responsive">
  <table class="responsive-table table-striped table-hover">
    <thead>
      <tr class="bg-white text-uppercase fs-sm">
        <th class="text-center tippy" width="50" data-tippy-content="Tipo de pagamento">Ano</th>
        <th class="text-center tippy" width="70" data-tippy-content="Número do pedido">Mestrando</th>
        <th class="text-center" width="400">Titulo</th>
        <th class="text-center">Link Documento</th>
        <th class="text-center">Banca Avaliadora</th>
      </tr>
    </thead>
    <tbody>
      <% @dissertations.each_with_index do |dissertation, i| %>
        <%= render 'dissertation', dissertation: dissertation, i: i %>
      <% end %>
    </tbody>
  </table>
</div>
<div class="paginateBox <%= 'no-records' if @dissertations.count.zero? %>">
  <%= paginate @dissertations %>
  <%= page_entries_info @dissertations %>
</div>

app/views/dissertations/new.html.erb
<h1>New dissertation</h1>

<%= render "form", dissertation: @dissertation %>

<br>

<div>
  <%= link_to "Back to dissertations", dissertations_path %>
</div>

app/views/dissertations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dissertation %>

<div>
  <%= link_to "Edit this dissertation", edit_dissertation_path(@dissertation) %> |
  <%= link_to "Back to dissertations", dissertations_path %>

  <%= button_to "Destroy this dissertation", @dissertation, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrawlerPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>